apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  name: frp-tunnel
spec:
  controller: k8s.codecrafts.cf/frp-tunnel-ingress-controller
